### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -L alo,ans,bu,clen,inout,parms,ro,som`

### CODE REVIEW

**Comment by cenit** [comment]
thanks!
could you please fix alignment in femm/femm.rc?

**Comment by cenit** [comment]
another great addition if you are confident enough would be adding the codespell action on the github yaml

https://github.com/codespell-project/actions-codespell

**Comment by luzpaz** [comment]
> thanks! could you please fix alignment in femm/femm.rc?

what line?

> another great addition if you are confident enough would be adding the codespell action on the github yaml  

It should be easy to via https://github.com/marketplace?type=&verification=&query=codespell+

**Comment by cenit** [comment]
> > thanks! could you please fix alignment in femm/femm.rc?
> 
> 
> 
> what line?
> 

459, 658, ...
they are very apparent in the diff
Every spell correction in that file has misaligned spacing in code due to a letter added to the string.
Another option is just running clang-format on all the code after your spell check


> 
> > another great addition if you are confident enough would be adding the codespell action on the github yaml  
> 
> 
> 
> It should be easy to via https://github.com/marketplace?type=&verification=&query=codespell+

yes, i put another link where they explained it. I was asking if you had time to add it to this PR or not, anyway it's fine

**Comment by luzpaz** [comment]
> I was asking if you had time to add it to this PR or not, anyway it's fine

I'd rather not add it to this PR just because it may need tweaking and create more `git log` clutter.

> 459, 658, ...
> they are very apparent in the diff  

Thanks! Fixed now in [e602859](https://github.com/cenit/FEMM/pull/9/commits/e602859740c699b588174ebbc66605f6e8a34140) I wasn't clear what you meant by 'alignment' originally. (I'm used to folks annotating the diff directly via the github UI, it's easier to understand in context then).

**Pull request merged**
